CREATE SCHEMA PRICE_SCHEMA;
SET MODE ORACLE;
SET SCHEMA PRICE_SCHEMA;

CREATE TABLE PRICE
(
    ID INTEGER NOT NULL,
    VENDOR_ID INTEGER NOT NULL,
    INSTRUMENT_ID varchar2 NOT NULL,
    PRICE NUMBER(38, 0) NOT NULL,
    CURRENCY CHAR(3) NOT NULL,
    CREATED_ON DATE DEFAULT CURRENT_DATE  NOT NULL
);

ALTER TABLE PRICE ADD CONSTRAINT SKEY1 PRIMARY KEY (ID);

CREATE INDEX IX_PRICE_SERVICE_VENDOR ON PRICE (VENDOR_ID);
CREATE INDEX IX_PRICE_SERVICE_INSTRUMENT ON PRICE (INSTRUMENT_ID);

CREATE SEQUENCE PRICE_ID_SEQ START WITH 10000000 INCREMENT BY 1;